### ISSUE TITLE
running server

### ISSUE THREAD

**Issue by andyfen** [benhowdle89/isomorphic-js-app#1]
When i run

node app.js

on page refresh i get this ? 

TypeError: Cannot read property 'pathname' of undefined
   at _.extend.matchRoot (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/backbone/backbone.js:1557:51)
   at _.extend.loadUrl (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/backbone/backbone.js:1731:17)
   at Object.module.exports.init (/Users/user/Documents/backbone/isomorphic-js-app/assets/controller.jsx:34:20)
   at Layer.handle [as handle_request](/Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/lib/router/index.js:302:13)
   at /Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/lib/router/index.js:261:10)
   at SendStream.error (/Users/user/Documents/backbone/isomorphic-js-app/node_modules/express/node_modules/serve-static/index.js:107:7)
   at SendStream.emit (events.js:107:17)

**Comment by tdlm** [comment]
I get the same thing.

**Comment by codecvlt** [comment]
same!
